### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by jl2005** [M42-Orion/163musicDownload#1]
下载的歌单是：https://music.163.com/#/playlist?id=2043625845

错误日志是：
Traceback (most recent call last):
  File "./m.py", line 62, in <module>
    main(url=url)
  File "./m.py", line 53, in main
    results_json = request(url)
  File "./m.py", line 30, in request
    results_json = json.loads(results.text)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by M42-Orion** [comment]
问题应该是你的python版本不对吧，你是不是2.7的python版本？

**Comment by jl2005** [comment]
> 问题应该是你的python版本不对吧，你是不是2.7的python版本？

已经用别的工具下载了，下次有机会我再试试

**Comment by M42-Orion** [comment]
> > 问题应该是你的python版本不对吧，你是不是2.7的python版本？
> 
> 已经用别的工具下载了，下次有机会我再试试



> > 问题应该是你的python版本不对吧，你是不是2.7的python版本？
> 
> 已经用别的工具下载了，下次有机会我再试试

**Comment by M42-Orion** [comment]
> > 问题应该是你的python版本不对吧，你是不是2.7的python版本？
> 
> 已经用别的工具下载了，下次有机会我再试试

现在API已经关闭，不能使用了
